name: truyenhot_frontend_deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Commit Message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"

      - name: Set up SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to server
        id: deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "Deploying..."
          sshpass -p "$SSH_PASSWORD" ssh $SSH_USER@$SSH_HOST << EOF
            cd /var/www/truyenhot_FE
            # Pull từ git về 
            git checkout -- yarn.lock
            git pull 
            
            # Cài đặt các dependencies
            yarn install
            yarn build

            # Check process
            if pm2 list | grep -q 'truyenhot-backend'; then
              echo "Dừng và xoá process..."
              pm2 stop truyenhot-backend
              pm2 delete truyenhot-backend
            else
              echo "Không có process hoạt động."
            fi

            # Chạy pm2
            pm2 start ./ecosystem.config.cjs --env production || { echo "Khởi chạy process pm2 thất bại!"; exit 1; }

            echo 'Deploy thành công!'
          EOF
